blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

config/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include


def index(request):
    return render(request, 'base.html')


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('sign_up/', include('accounts.urls')),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))

]

posts/urls.py
from django.urls import path

from .views import *

app_name = 'posts'

urlpatterns = [

    path("", index, name="index"),
    path("detail/<int:id>/", detail, name="detail"),
    path("create/", create_view, name="create"),
    path("edit/<int:id>/", edit_view, name="edit"),
    path("delete/<int:id>/", delete_view, name="delete"),
]

posts/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils import timezone


class CustomManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='PB')

    def delete(self, id):
        return super().get_queryset().filter(id=id).update(status='DF')


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_posts')
    status = models.CharField(
        max_length=2,
        choices=Status,
        default=Status.PUBLISHED,
    )
    objects = models.Manager()
    published = CustomManager()

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'posts'
        ordering = ['-publish']

posts/forms.py
from django import forms

from posts.models import Post


class PostCreatModel(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'publish', 'status']

        widgets = {
            'publish': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}),
        }

        def clean_title(self):
            pass

posts/views.py
from django.contrib.admin.templatetags.admin_list import paginator_number
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from posts.models import Post
from .forms import PostCreatModel


# Create your views here.
# @login_required(login_url='login')
def index(request):
    posts = Post.published.all()
    q = request.GET.get('q')
    if q and q != "None":
        posts = posts.filter(title__icontains=q) | posts.filter(body__icontains=q)

    paginator = Paginator(posts, 5)  # paginationga limit berilvot
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)  # postni bolib chiqvotdi shu yerda

    # page = request.GET.get('page')
    # print(page)

    return render(request, 'post/list.html', {
        'q': q,
        'posts': posts

    })


def detail(request, id):
    post = Post.published.filter(id=id).first()
    return render(request, 'post/detail.html', {'post': post})


def create_view(request):
    if request.method == "POST":
        form = PostCreatModel(request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts:index")

    else:
        form = PostCreatModel()

    return render(request, 'post/create.html', context={'forms': form})


def edit_view(request, id):
    if request.method == "POST":
        posts = Post.published.get(id=id)
        form = PostCreatModel(request.POST, instance=posts)
        if form.is_valid():
            form.save()
            return redirect("posts:index")
        return render(request, 'post/edit.html', context={
            'form': form,
            'posts': posts

        })
    posts = Post.published.get(id=id)
    form = PostCreatModel(instance=posts)
    return render(request, 'post/edit.html', context={
        'form': form,
        'posts': posts
    })


def delete_view(request, id):
    Post.published.delete(id=id)
    return redirect("posts:index")

templates/post/create.html
{% extends 'base.html' %}

{% block title %}
    create
{% endblock %}

{% block content %}

    <form action="{% url 'posts:create' %}" method="post">
    {% csrf_token %}
        {{ forms }}
        <input type="submit" value="create">
    </form>
{% endblock %}

templates/post/detail.html
{% extends 'base.html' %}

{% block title %}
    detail
{% endblock %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">title</th>
            <th scope="col">body</th>
            <th scope="col">publish</th>
            <th scope="col">status</th>
        </tr>
        </thead>

        <tbody>
        <tr>
            <td>title: <a href=""> {{ post.title }}</a></td>
            <td>body: {{ post.body }}</td>
            <td>{{ post.publish }}</td>
            <td>{{ post.status }}</td>
        </tr>
        </tbody>

    </table>
    <a href="{% url 'posts:index' %}" class="btn btn-danger"> back to home </a>

{% endblock %}

templates/post/edit.html
{% extends 'base.html' %}


{% block title %}
    edit
{% endblock %}

{% block content %}
    {{ form.id }}
    <form action="{% url 'posts:edit' posts.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary">


    </form>

    <a href="{% url 'posts:index' %}" class="btn btn-danger"> back to home </a>



{% endblock %}

templates/post/list.html
{% extends 'base.html' %}


{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">title</th>
            <th scope="col">body</th>
            <th scope="col">publish</th>
            <th scope="col">status</th>
            <th scope="col"> action</th>
        </tr>
        </thead>

        {% for post in posts %}
            <tbody>
            <tr>

                <td><a href="{% url 'posts:detail' post.id %}" class="btn btn-outline-primary"> {{ post.title }}</a>
                </td>
                <td>{{ post.body }}</td>
                <td>{{ post.publish }}</td>
                <td>{{ post.status }}</td>
                <td>
                    <a href="{% url 'posts:edit' post.id %}"> edit</a>

                    <a href="{% url 'posts:delete' post.id %}" class="btn btn-outline-danger"> delete</a>
                </td>
            </tr>
            </tbody>

        {% endfor %}

    </table>

   {% include 'post/pagination.html'  with page=posts %} {# posts bu data basadan kevotgan postlari #}

    <a href=" {% url 'posts:create' %}" class="btn  btn-dark"> create </a>

{% endblock %}

templates/post/pagination.html
<nav aria-label="...">
    <ul class="pagination">

        {#         Previous #}
        {% if not  page.has_previous %}



            <li class="page-item disabled">
                <a class="page-link" href="?page=" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
        {% else %}
            <li class="page-item ">
                <a class="page-link" href="?page={{ page.previous_page_number }}&q={{ q }}">Previous</a>
            </li>
        {% endif %}


        {#        digits   page larni sonlari  #}

        {% for p in page.paginator.page_range %}

            {% if p == page.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page{{ p }}&q={{ q }}">{{ p }}</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ p }}&q={{ q }}">{{ p }}</a></li>

            {% endif %}

        {% endfor %}

        {#  page number tugadi #}

        {% if not  page.has_next %}
            <li class="page-item disabled">
                <a class="page-link" href="?page=" tabindex="-1" aria-disabled="true">Next</a>
            </li>
        {% else %}
            <li class="page-item ">
                <a class="page-link" href="?page={{ page.next_page_number }}&q={{ q }}">Next</a>
            </li>
        {% endif %}

    </ul>
</nav>